name: C/C++ CI

on:
  push:
    branches:
    - 'master'
    - 'develop'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:

  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: configure
        run: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/release/install -DBUILD_BACKEND=ON -DBUILD_SHARED_LIBS=OFF -j 2 -Bbuild/release -S.
      - name: build
        run: cmake --build build/release -j 2 --config Release --target install
      - name: Publish artefacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/release/install/bin/mavsdk_server_bin.exe'
          asset_name: 'mavsdk_server_macos'
          tag: ${{ github.ref }}
          overwrite: true
